name: .NET Labs Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: [ Laboratory.First ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.lab }}

    - name: Build solution
      run: dotnet build ${{ matrix.lab }} --configuration Release /p:GenerateDocumentationFile=true

    - name: Run tests
      run: dotnet test ${{ matrix.lab }} --configuration Release --no-build --verbosity normal

    - name: Publish all projects into one folder
      run: dotnet publish ${{ matrix.lab }} --configuration Release -o out/${{ matrix.lab }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.lab }}
        path: out/${{ matrix.lab }}/**